### ISSUE TITLE
Backing sounds shouldn't be confuse-able with sound effects

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#100]
Specifically, `108_4_fill_0_autumn.wav` has a little chime at around the 7 second mark. Effects like that chime could seem to the user like it came from some mapped sound-parameter (like some trend-line break or something like that)

**Comment by Rex2002** [comment]
maybe also the backing volume should be reduced a little bit in general (either code-side or sample-side, though I suppose code sided is simpler), because it tends to be louder than the synths

**Comment by MalteRichert** [comment]
Good points. I'll fix the volume in the mixer and will try to make more boring beats for the final backings xd
