### ISSUE TITLE
Padding when data aren't available

### ISSUE THREAD

**Issue by MalteRichert** [Rex2002/sound-investments#112]
I think this is not where it should be yet. When a stock isn't available for a long time at the beginning (eg Alibaba from 2000 on) the pitch just plays the lowest note, the graphs show a line on zero and the EQMOVAVG triggers an event at every quarter note.

**Comment by Rex2002** [comment]
this happens since we don't have values for "do not play" when padding, we simply set the padded values to zeros, which then results in the lowest note being played, etc.

**Comment by Rex2002** [comment]
the harmonizer now is able to recognize "not available" (represented by -1.0) as per #109
