### ISSUE TITLE
Options in Choice-Box for Mapping are not refreshed properly

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#113]
When mapping an instrument with some parameter, then changing the instrument and then going back to the same instrument, the parameters lack the one that was mapped previously. This might either be because we don't actually remove the parameter from the mapping or because we fail to refresh the options for the choice box.

I will look into this tomorrow, just wanted to write this down to not forget

**Comment by nichtLehdev** [comment]
That's the one I just encountered. Wanted to look into this but couldn't find the method were the Options get removed/hid and visible again.

**Comment by nichtLehdev** [comment]
Did a bit more testing and as soon as the stock on which the instrument got changed gets removed, the Option is available for other Stocks again.
