### ISSUE TITLE
Rebase "Magic Numbers" into constants

### ISSUE THREAD

**Issue by nichtLehdev** [Rex2002/sound-investments#116]
As mentioned while presenting, constants would make more sense to Kruse

**Comment by MalteRichert** [comment]
started resolving this in [6207510](https://github.com/Rex2002/sound-investments/commit/6207510b57d9a65f5fe2ab41f8eceb7abd0065c2)
Have left all Constants in the methods because the vast majority is only used in one method. Only `0` now has about four or five constants which seems a little weird.

**Comment by nichtLehdev** [comment]
Already Resolved
