### ISSUE TITLE
Test DataAnalyzer

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#124]
Just thought I would open an issue for you, since you're working on it.

To recap the idea behind how to implement the tests (as I understood it):
1. Write Test-Price-Data in the `resources/` folder. These should look like the `TestPrices.json` file that is already there (though it doesn't have to be as long of course). The test-data is meant to include certain formations.
2. Go into `DataRepo.java` and set the static variable `GET_PRICES_DYNAMICALLY` to `false`. Then go to the static `testPrices()` method and change the `fname` variable to point to the json written in step 1.
3. Run the app, include the formation in the mapping and see if we get the expected result

**Comment by nichtLehdev** [comment]
Thanks for the explanation :D @JakobPK I'll start final testing on Saturday. Would be great if you could start with data till then. If not please provide me with some sort of graph that's usable for the different Forms and I'll try to match it with the corresponding data

**Comment by JakobPK** [comment]
@nichtLehdev mein output in triangle isnt what i'd expect, i'll check the issue but if ur testing test that one after i fixed it pls

**Comment by ArtInLines** [comment]
@nichtLehdev @JakobPK Are the tests for the data-analyzer done (and successful)?

**Comment by nichtLehdev** [comment]
No yet. Currently working on it

**Comment by JakobPK** [comment]
Einzelnd funktionieren alle wie sie wollen, müssen nur noch im gesamten getestet werden
