### ISSUE TITLE
Technische Doku erstellen

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#125]
Die Idee war, glaube ich, dass wir einige JavaDoc-Kommentare einbinden und dann nur kurze Beschreibungen zum generellen Vorgehen und der Datei-Struktur in READMEs der jeweiligen Packages haben.

Muss erst zur Abgabe fertig sein, aber ich dachte, ich würde schonmal ein Issue für aufmachen

**Comment by Rex2002** [comment]
started for audio in #184

**Comment by nichtLehdev** [comment]
finalized Harmonizer in #199
