### ISSUE TITLE
Standort-Filter funktional machen oder aus UI rausnehmen

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#126]
Um es funktional zu machen, bräuchten wir Änderungen beim Einholen der Liste von Sonifiables im DataRepo. Siehe auch #18 dafür. Ansonsten ist der Filter auch nicht wirklich wichtig und kann einfach aus der UI entfernt werden

**Comment by Rex2002** [comment]
Standort wurde entfernt
