### ISSUE TITLE
Cleanup resources folder

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#133]
The resources folder is currently cluttered with files needed by different components without structure (excluding the audio resources). This should be cleaned up by packing the resources of different components together into subfolders

**Comment by MalteRichert** [comment]
closely related to #155

**Comment by ArtInLines** [comment]
resolved in afb5b49 and b09630d - not merged into main yet

**Comment by ArtInLines** [comment]
Merged to main now
