### ISSUE TITLE
Instrument List doesn't refresh after changing mapping

### ISSUE THREAD

**Issue by MalteRichert** [Rex2002/sound-investments#157]
The Instrument List works great for setting a mapping initially but it doesn't refresh when the mapping is changed.

In the screenshot, strings and sleigh bell were selected initially but are still shown when the mapping is changed to retro synth and bike bell.
<img width="1145" alt="image" src="https://github.com/Rex2002/sound-investments/assets/103412886/889cf00a-1f52-498b-8320-fa6cd94b0a83">

**Comment by ArtInLines** [comment]
seems to be fixed with 920ffd7 as well. @MalteRichert can you confirm that the issue is solved with 920ffd7 too?

**Comment by MalteRichert** [comment]
Yap, it's fixed on current main.
