### ISSUE TITLE
Architektur & Schnittstellen erstellen und abstimmen

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#16]
- [x] Architektur besprechen
- [x] Überschriften für Entwurf festlegen
- [x] Entwurf fertig stellen
- [x] Entwurf abschicken

**Comment by ArtInLines** [comment]
- [ ] Architektur besprechen
- [ ] Überschriften für Entwurf festlegen
- [ ] Entwurf fertig stellen
- [ ] Entwurf abschicken

**Comment by MalteRichert** [comment]
Entwurf abgeschickt am 19.05.2023.
