### ISSUE TITLE
Meta/Facebook returns empty response

### ISSUE THREAD

**Issue by MalteRichert** [Rex2002/sound-investments#165]
Trying to map Meta/Facebook always leads to an error because the api returns an empty JSON for the [link](https://api.leeway.tech/api/v1/public/intraday/FB.NASDAQ?apitoken=ftd5l4hscm9biueu5ptptr&from=2023-05-06&to=2023-06-11&interval=5m). We should probably just remove the stock from the default list.

**Comment by ArtInLines** [comment]
Should be solved with #188 because we only get sonifiables from the same api that we get the price data from as well
