### ISSUE TITLE
UI doesn't update Synth-Box after using Back-Button

### ISSUE THREAD

**Issue by nichtLehdev** [Rex2002/sound-investments#173]
<img width="1080" alt="Screenshot 2023-06-10 at 15 06 23" src="https://github.com/Rex2002/sound-investments/assets/87381979/c950c31d-49f3-4ae0-9327-f4613a9e6c95">

**Comment by nichtLehdev** [comment]
As shown in previous comment, after using the back button in the playback screen I can change the Synth and it won't update in the box on the right

**Comment by Lizzyhara** [comment]
Oki schaue es mir an

**Comment by Lizzyhara** [comment]
VBox hat richtige Children, und beim initialiseiern funktioniert auch noch das Updaten. Danach nichtmehr 
=> FXML fehler 
Children not displaying

Unteranderem probiert: 
Rückgabe geändert,
vorher @FXML
überprüfen ob die wo anders noch geändert wird: NEIN deshlab nur display Fehler

Lösung: nochnicht gefunden

**Comment by ArtInLines** [comment]
@Lizzyhara hast du gecheckt, dass das Mapping richtig updatet. Soweit ich den Code in Erinnerun habe, fügt der MainSceneController ein Callback beim Mapping hinzu und nur wenn das Mapping sich verändert wird dieser Callback aufgerufen und die Child-Nodes bei der VBox hinzugefügt

**Comment by Lizzyhara** [comment]
also das Problem ist behoben wenn man die 
        mapping.setOnInstrAdded(inst -> instAdded(inst.toString()));
        mapping.setOnEvInstrAdded(inst -> instAdded(inst.toString()));
        mapping.setOnInstrRemoved(inst -> instRemoved(inst.toString()));
        mapping.setOnEvInstrRemoved(inst -> instRemoved(inst.toString())); 
in die ShowMapping macht aber die zeigen sich natürlich nicht dann beim ersten mal an

**Comment by Lizzyhara** [comment]
Die VBox hat die Children

**Comment by Lizzyhara** [comment]
mapping.setOnInstrAdded(inst -> instAdded(inst.toString()));
        mapping.setOnEvInstrAdded(inst -> instAdded(inst.toString()));
        mapping.setOnInstrRemoved(inst -> instRemoved(inst.toString()));
        mapping.setOnEvInstrRemoved(inst -> instRemoved(inst.toString()));

in Line 124 zu packed solves the error fast vollständig müssen nur height anpassen noch

**Comment by Lizzyhara** [comment]
udn sonst das rausnehmen naürlich

**Comment by Lizzyhara** [comment]
nvm

**Comment by ArtInLines** [comment]
Ok scheint als hättest du einen Plan wo der Fehler liegt und wie er zu beheben ist, oder?

**Comment by Lizzyhara** [comment]
ja also dass Problem ist jz eig behoben glaube ich gib mir noch 5 min

**Comment by Lizzyhara** [comment]
ein problem ist noch dass er alle inst bekommt und auch die auf null gesetzten anzeigt

**Comment by Lizzyhara** [comment]
Sollte gefixt sein, nicht umbedingt hübsch (
   Verbesserung, wenn instAdded nie null bekommt bei der Übergabe
)
aber sonst ist das Issue fixed

**Comment by MalteRichert** [comment]
@Lizzyhara denkst du noch daran zu pushen und einen PR zu öffnen?
