### ISSUE TITLE
Data-Repo spezifizieren & implementieren

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#18]
Die Data-Repo Klasse (in Malte's Sequenzdiagramm auch "Data-Handler" genannt) bietet eine Abstraktion zum Erhalten der Daten. Die Spezifizierung dieser Klasse ist Teil der Architektur (#16).

- [x] Spezifizierung ausarbeiten & absprechen
- [x] Add local testing data to prevent too many API calls during development
- [x] API-Calls hinter API verstecken (z.B.: `getStock()` versteckt API-Calls die im Hintergrund ausgeführt wird)
- [x] Caching von API-Responses implementieren
- [x] Multithreading, um API-Requests non-blocking zu machen
- [x] Synchronizaton von cached API-Responses im Hintergrund ausführen

The DataRepo basically has all features implemented already, however, there are still several issues & todos:
- [x] Add better Error Handling for API-requests, specific to the API that is being talked to
- [x] Get list of ETFs & Indices along with Stocks (& cache them as well)
- [x] updateSonifiablesList() should update ETFs & Indices too, once we get them
- [x] Refactor updateSonifiablesList() to reduce code duplication
- [x] Get Price-data in a loop, to not just get some of the requested data
- [x] Make different API-requests depending on the wanted interval-length
- [x] Get price data for different sonifiables simultaneously
- [ ] Use APIs other than just Leeway to get Price-data too if possible
- [ ] Add de-facto pagination to price-requests to allow parallelization
- [ ] Improve pagination-handler to be more flexible and useful
- [ ] Cache for each Sonifiable / Exchange which APIs provide us price-data to them
- [x] ~~Debug fallback API-request in getTradingPeriods() as it seems to always throw errors~~ getTradingPeriods was purged

**Comment by MalteRichert** [comment]
@ArtInLines are you still working on this?

**Comment by ArtInLines** [comment]
Yes. The multithreading is still giving me some headaches and I need to refactor the code to remove all the testing parts then.

**Comment by ArtInLines** [comment]
Closing because all remaining tasks are rather low priority
