### ISSUE TITLE
Unused Dependencies?

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#196]
I noticed that I had no idea what some of our dependencies in our pom.xml were doing or what they are used for.

Especially `com.groupdocs` seems completely unused. Is anybody using that dependency (and for what?) or can we remove that?

Also, the `org.jfree` dependency seems to only be used for testing the synth. Can we remove that when we build the final deliverable?

@MalteRichert @Rex2002 Afaik you are using Lombok at certain places, right? I didn't actually find where you use that, but I also didn't look too hard xD. I presume we can not remove that dependency, right? And as far as I understand lombock, it should also not increase the size of the final deliverable (except for necessary boilerplate), right?

**Comment by MalteRichert** [comment]
I agree with removing the Synth test, @Rex2002 has to give the final go on that though. 
On Lombok: we use that for `@data` on some data classes like `InstrumentMappingRaw` I think. So please don't remove that.

**Comment by ArtInLines** [comment]
Won't remove that, no worries. You also have no idea why we have  `com.groupdocs` as a dependency though, do you?

**Comment by MalteRichert** [comment]
Nope, I'm pretty sure that audio doesn't use those; our code is pretty bare bones. Maybe @JakobPK does some fancy data stuff with that?

**Comment by Rex2002** [comment]
`com.groupdocs` is a remnant of audio-testing, was used for file-type-conversion, can be removed

**Comment by ArtInLines** [comment]
👍
