### ISSUE TITLE
Funktionalität an UI anbinden

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#20]
Kommunikation zwischen UI und Data-Repo (#18) sowie Aufrufen des Synthesizers.

Das sollte aber wahrscheinlich noch warten bis die Architektur finalisiert wurde.

**Comment by ArtInLines** [comment]
Architektur wurde besprochen & Kommunikation zwischen UI und StateManager soll in #33 getestet werde

**Comment by MalteRichert** [comment]
@ArtInLines this is done, right?

**Comment by ArtInLines** [comment]
True, thx for the reminder :)
