### ISSUE TITLE
Parameter disappears when synth gets changed

### ISSUE THREAD

**Issue by nichtLehdev** [Rex2002/sound-investments#200]
I thought we already fixed this. But as seen in the Screenshot once I remove the Synth from one field where a param (i.e. Pitch was mapped) this param doesn't appear in the list anymore.

Tested this on main and global-cleanup

For the fix: Please wait till #199 gets merged or base the branch on global-cleanup. 

<img width="839" alt="Screenshot 2023-06-11 at 07 43 54" src="https://github.com/Rex2002/sound-investments/assets/87381979/4569ecf0-fd1a-4683-9041-ea8243b4d012">

**Comment by Lizzyhara** [comment]
Could you check out ui_choices branch an look up if the error is persistend in it. I am not sure if it is fixed or I am just dumbfounded to get it again right now.

**Comment by nichtLehdev** [comment]
Seems to work fine for me too 👍

**Comment by Lizzyhara** [comment]
Than I ll close this iusse.
