### ISSUE TITLE
Audio-Playback implementieren

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#21]
Angenommen der Synthesizer ist fertig uns gibt uns einen Audio-Stream aus, dann muss die UI Playback-Buttons zur Steuerung des Audio-Streams anbieten.

Dafür ist die fertige Architektur unabdingbar, da die Schnittstellen zwischen UI und Synthesizer klar sein müssen

**Comment by MalteRichert** [comment]
Update: Die Playback-Schnittstelle existiert vollständig. Hier fehlen nur noch die restlichen Buttons im UI

**Comment by ArtInLines** [comment]
UI ist funktional an Playback-Schnittstelle angebunden, es fehlen nur noch zwei Teile:
- [ ] weitere Playback-Buttons (mit Icons)
- [ ] Drag-&-Drop für Slider
