### ISSUE TITLE
Apple Inc (AAPL) appears twice in search list

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#212]
I presume that they are two different Apple stocks at different exchange markets. But since we don't show the symbol of the exchange in the search result, it becomes confusing. Either we also show the exchange's symbol or we simply remove any stocks with duplicate IDs

**Comment by nichtLehdev** [comment]
This doesn't only happen to AAPL but actually to all Apple Stocks

**Comment by ArtInLines** [comment]
resolved in e327837
