### ISSUE TITLE
V-Form doesn't get recognised correctly (I think)

### ISSUE THREAD

**Issue by nichtLehdev** [Rex2002/sound-investments#221]
<img width="1484" alt="Screenshot 2023-06-11 at 15 09 17" src="https://github.com/Rex2002/sound-investments/assets/87381979/9a063952-68ec-47e9-9dbc-19c5078b85cf">

Mapping:
TestVPrices.Preis -> Pitch
TestVPrices.V-From -> On Off

Result:
Only plays between the 2 markers. Not in the V-Formation beforehand (where it should play in my opinion)

**Comment by JakobPK** [comment]
zep cuy current code is not merged with main, its on branch issue #170

**Comment by JakobPK** [comment]
Fixed the issue, its in branch issue #170 because i didnt want to open a new one. It works for me now and i tested it with several input values. So it should work.
