### ISSUE TITLE
UI: Legend-key swaps names when sonifying two stocks

### ISSUE THREAD

**Issue by MalteRichert** [Rex2002/sound-investments#228]
<img width="1479" alt="image" src="https://github.com/Rex2002/sound-investments/assets/103412886/3c39bcb4-06f8-4ff9-a91b-ba1ac6943c7d">
The pink line should definitely be Apple but is shown to be ABIVAX. Also, I suspect that ABIVAX shouldn't exist for the early 80s only but for the more recent years. Something seems to be wrong with the dates/padding there

**Comment by Rex2002** [comment]
maybe related to #214 ?

**Comment by ArtInLines** [comment]
I'm working on #214 rn, so I can take a look at this too

**Comment by nichtLehdev** [comment]
Oh so you got that issue too.. I couldn't replicate it and thought I looked wrongly the one time

**Comment by Lizzyhara** [comment]
colors[sonifiableNames.length-i] in MusicSceneConroller line 164 should fix it.

**Comment by Lizzyhara** [comment]
Will be tested  once we get our new api keys.

**Comment by ArtInLines** [comment]
@Lizzyhara mit neuen API-Keys getestet und das scheint nicht zu funktionieren:
![grafik](https://github.com/Rex2002/sound-investments/assets/64645307/931c3216-aa8e-4e1a-8efa-0a9c7e7426bb)

**Comment by ArtInLines** [comment]
I think the issue is int he StateManager around line 297. The musicDataPrices is not guaranteed to be parallel to the sonifiableNames. I will check if that fixes the issue shortly

**Comment by Lizzyhara** [comment]
colors[sonifiableNames.length-i-1] in MusicSceneConroller line 164 fixxes it. But it is not a beautiful solution shall I push it or better not ?

**Comment by ArtInLines** [comment]
@Lizzyhara I'm very sure that that wouldn't actually work for different inputs. The problem is that the prices are ordered differently than the names. I fixed that in #238. Your solution would most probably only work sometimes

**Comment by Lizzyhara** [comment]
oki
