### ISSUE TITLE
"Zurück" button looks smaller than "export" button

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#235]
In the music scene the "Zurück" button looks smaller than the "export" button. I have no idea why, because the values for them in the fxml are the same 🤷
Not really important, just nice to have, if they looked the same

**Comment by Lizzyhara** [comment]
Should be a quick fix, I am  on it.

**Comment by ArtInLines** [comment]
amazing thx

**Comment by Lizzyhara** [comment]
fixxed
