### ISSUE TITLE
Deliverable vorbereiten

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#24]
Wir brauchen wieder ein Executable or CMD-Skript, damit der Kruse die App mit einem einzelnen Click öffnen kann.

Da ich das mit JavaFX letztes Semester schon irgendwie hinbekommen habe, kann ich das gerne wieder machen.

**Comment by ArtInLines** [comment]
see #121

**Comment by ArtInLines** [comment]
The building process is broken on my machine now. Using `mvn clean package` to create the `.jar` file fails. The issue seems to come from Lombok annotations. For example, one error message points me to `EvInstrMapping` and tells me that the `getData()` method doesn't exist.

@MalteRichert do you mayhaps know if I need to set anything up to have lombok working on my machine?

**Comment by MalteRichert** [comment]
Hmm that's weird. I think it might have something to do with changing for not modular structure to modular and maybe maven needs to be told what modules to include for build somehow. Though I'd have thought that module-info.java does that

**Comment by ArtInLines** [comment]
Hmmm ok, I'll look more into it then. Thought you might already have some idea what's going on

**Comment by Rex2002** [comment]
seems to be something with lombok annotation processing, 
`<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>RELEASE</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>`

solved the problem for me (package the jar worked, havent tested full workflow yet)

**Comment by ArtInLines** [comment]
hmm maybe. This error can only really come from the getResource() not working as intended. I'll look into it later
