### ISSUE TITLE
Specify Chart Analysis

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#32]
- [x] Write down which Chart Analyses exist
- [x] Decide exactly which of these Analyses we want to implement
- [x] Write down what these Chart Analyses tell us
- [x] Write down implementation ideas for the Chart Analyses
- [x] Write infos to Chart Analysis in Entwurf

**Comment by JakobPK** [comment]
Implementationsspezifikation der ChartAnalyse muss in Entwurf
