### ISSUE TITLE
Playback

### ISSUE THREAD

**Issue by Rex2002** [Rex2002/sound-investments#44]
- [x] find out where the blocking part of current playing mechanism is
    sourceDataLine.play is blocking part
- [x] develop playback-mechanism that allows pause/play & skipping
    see c73d9b4f5635be6850d9d9629c5d24ef5c4d63b5
- [ ] add getters to allow UI to get current playback state
- [ ] if it uses additional threads: align with state-manager thread-handling

**Comment by Rex2002** [comment]
also relates to #21

**Comment by ArtInLines** [comment]
Ergibt Sinn für mich. Ich hatte zwei Punkte, die sich noch verbessern ließen und war jetzt mal so frei und habe die einfach hinzugefügt (hoffe das ist ok).
1. Der Check ob die EventQueue leer ist, sollte in einer Schleife passieren, weil mehrere Werte in der Queue liegen können (falls der User schnell genug klickt). Ansonsten wäre ein einfacher Mutex auch besser als eine EventQueue
2. Ich habe einen Check hinzugefügt, um sicherzustellen, dass der positionPointer nicht underflows. Als ich gerade eben damit ein wenig herumgespielt habe ist das nämlich passiert nachdem "jb" oft genug gespammt habe.

Diese Steuerbefehle von der UI zu schicken sollte, soweit ich das sehe, auch kein Problem sein. Wobei ich für bessere Readability statt Integers wahrscheinlich eher bestimmte Enum-Werte schicken würde.

Btw der Test, den du hier gebaut hast ist schon richtig fancy, gefällt mir 👍

**Comment by Rex2002** [comment]
ist jetzt (0d16e1e52b6bee9b5518b300f3ee0b9f4c3ff809) in eigener Klasse, 
offen ist jetzt aber noch, wann der Playback-Thread terminiert, entweder wenn Audio einmal durchgelaufen ist oder wenn vom User explizit der kill kommt (und sonst nichts mehr abspielen aber für messages wie "reset to 0" bereit bleiben)

**Comment by Rex2002** [comment]
allowed actions: play, pause, skip forward, skip backward, reset, stop
only "stop" kills the thread, otherwise all options are always possible (though limited in their result, e.g. skip forward beyond end of sound is obviously not possible)

**Comment by ArtInLines** [comment]
Gefällt mir sehr gut 👍 Sobald @Lizzyhara ihre Änderungen an der UI gefixt und gepusht hat, können wir das mit der UI verbinden und die letzten beiden ToDos hier abhaken
