### ISSUE TITLE
bug: Verification of mapping doesn't always work

### ISSUE THREAD

**Issue by MalteRichert** [Rex2002/sound-investments#76]
I just got the UI to load indefinitely twice, because the StateManager crashed with a ClassCastException "cannot cast LineData to RangeData". I assume this is because my mappings (Trend Line Break -> Filter On/Off) (Moving -> Filter On/Off) didn't make sense, but it shouldn't have been possible to even get that far.

**Comment by Rex2002** [comment]
+1 
Also encountered the possibility to map parameters that should not be allowed to be mapped. 
Noteworthy may also be, that I was able to map the bandwidth of the filter, while that parameter should not be mapable at all, I believe

**Comment by ArtInLines** [comment]
Should be fixed with f67ce18
The global parameters still don't work, but they will be fixed soon

**Comment by MalteRichert** [comment]
This can't happen anymore since only parameters of the correct type can be selected in drop-downs. Nicely done!
