### ISSUE TITLE
Validate amount of price-data

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#80]
The StateManager has to make sure that we have enough price data to produce audio of the requested length. If not, an error message should be shown to the user.

@MalteRichert @Rex2002 @nichtLehdev Any ideas on how a formula for that validation might look like? Like, what minimum length do the double-/boolean-arrays in the InstrumentDataRaw have to have to produce an audio stream of x seconds?

**Comment by MalteRichert** [comment]
Not needed right now
