### ISSUE TITLE
Cleanly exit App

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#82]
At the moment, we just call `System.exit` at the end of the app's lifetime (whether because of an error or bc the user closed the app). The reason behind that is that we have several threads and timers, that might still be running in the background. To cleanly exit the app, we would need to know at any moment which threads and timers are running, to cleanly close them.
This is, however, very low priority, because the OS will clean up after you anyways, so leaking resources (while not clean or pretty) is not really a problem

**Comment by MalteRichert** [comment]
Closing this due to low priority
