### ISSUE TITLE
Label Y-Axis and show audio length

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#83]
I feel that the Music-Scene should show either the Date-Range of the prices on the x-axis or the length of the audio stream or something like that. Otherwise the Music-Scene feels kinda empty to me, idk.

**Comment by MalteRichert** [comment]
Agreed. It would be really nice to have the dates displayed on the x-axis in some way

**Comment by MalteRichert** [comment]
This seems to have broken again. At least the numbers on the x-axis don't make any sense to me. Also: could we get units on both axes? Like I don't even know whether y-axis shows $ or € or just a relative index

<img width="1501" alt="image" src="https://github.com/Rex2002/sound-investments/assets/103412886/298a4941-19a5-4edc-b857-aab7a30a84fc">
