### ISSUE TITLE
Improve Error Message Display in UI

### ISSUE THREAD

**Issue by ArtInLines** [Rex2002/sound-investments#87]
Currently, the error message, that is displayed is far too big, with the text inside being bigger than necessary and it truncates any text that is more than a couple characters.
Furthermore, we might also want to factor the `displayError` out of the MainSceneController, as the MusicSceneController might also want to show errors in the same way. We might even want a function similar to `call()` in the StateManager, where we effectively have the try-catch block of running code that might throw errors factored out into said `call` function.

**Comment by MalteRichert** [comment]
Additional problem with Errors in UI: currently, after closing the error message the loading circle still spins and although the settings page stays responsive, I can't get it to start a new sonification. Could we reset the app in some way after an error message?

**Comment by ArtInLines** [comment]
Error Display shows the whole message as of #105 and the loading animation is stopped after an error in 965735a too
